name: "Deployment Action"
description: "This action is used to deploy subgraphs with relevant code changes from Messari subgraphs repository"
author: "Chris Steege"

inputs:
  HOSTED_SERVICE_ACCESS_TOKEN:
    description: "Access token for Messari's Hosted Service - TheGraph"
    required: true
  CHANGED_FILES:
    description: "String containing all changed files in the repository at the time of Github Aciton execution"
    required: true
  ABSOLUTE_PATH:
    description: "Returns the absolute path to the head of the repository running the action"
    required: true
  GRAPH_DEPLOYMENT_LOCATION:
    description: "Deployment location on TheGraph Hosted Service"
    required: true
  COMMIT_BEFORE_PUSH:
    description: "Commit hash before push to the repository"
    required: true
  COMMIT_AFTER_PUSH:
    description: "Commit hash after push to the repository"
    required: true
  
runs:
  using: 'node16'
  main: 'dist/index.js'